config/routes.rb
Rails.application.routes.draw do
  devise_for :users

devise_scope :user do
  authenticated :user do
    root 'transactions#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  resources :transactions
  resources :relative_activities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relative_activity.rb
class RelativeActivity < ApplicationRecord
    validates :entry_date,uniqueness:true
    validates :meditation,:inclusion => 0..10,:numericality => {:only_integer => true}
    validates :exercise,:inclusion => 0..10,:numericality => {:only_integer => true}
    validates :reading,:inclusion => 0..10,:numericality => {:only_integer => true}
    validates :concentration,:inclusion => 0..10,:numericality => {:only_integer => true}
    validates :hard_working,:inclusion => 0..10,:numericality => {:only_integer => true}
    validates :metal_stability,:inclusion => 0..10,:numericality => {:only_integer => true}
    validates :self_confidene,:inclusion => 0..10,:numericality => {:only_integer => true}
    validates :time_management,:inclusion => 0..10,:numericality => {:only_integer => true}
    validates :universal_power,:inclusion => 0..10,:numericality => {:only_integer => true}

def totalScore
    return meditation+exercise+reading+concentration+hard_working+metal_stability+self_confidene+time_management+universal_power
end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/relative_activities_controller.rb
class RelativeActivitiesController < ApplicationController

    def index
        @ractivities = RelativeActivity.all
        @med_data = {}
        @exer_data = {}
        @read_data = {}
        @conc_data = {}
        @hard_data = {}
        @metal_data ={}
        @self_data ={}
        @time_data ={}
        @univ_data ={}
        @min_data = {}

        @ractivities.each do |ractivity| 
            @med_data[ractivity.entry_date]=ractivity.meditation
            @exer_data[ractivity.entry_date]=ractivity.exercise
            @read_data[ractivity.entry_date]=ractivity.reading
            @conc_data[ractivity.entry_date]=ractivity.concentration
            @hard_data[ractivity.entry_date]=ractivity.hard_working
            @metal_data[ractivity.entry_date]=ractivity.metal_stability
            @self_data[ractivity.entry_date]=ractivity.self_confidene
            @time_data[ractivity.entry_date]=ractivity.time_management
            @univ_data[ractivity.entry_date]=ractivity.universal_power
            @min_data[ractivity.entry_date] = 4
        end

    end
    def new

    end

    def create
        @ractivity = RelativeActivity.new(post_params)
        if @ractivity.save
            redirect_to @ractivity
        else
            render plain: 'Unable to store Activity in the database'
        end
    end
    def show
        @ractivity = RelativeActivity.find(params[:id])

    end
    def destroy
        @ractivity = RelativeActivity.find(params[:id])
        @ractivity.destroy

        redirect_to relative_activities_path
    end

    private def post_params
        params.require(:post).permit(:entry_date,:meditation,:exercise,:reading,:concentration,:hard_working,:metal_stability,:self_confidene,:time_management,:universal_power)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    before_action :authenticate_user!
    def index
        @transactions = Transaction.all
        @credit_data = @transactions.map{
            |transaction|
        [transaction.amount] if transaction.transaction_type.to_s.eql?("credit")
    }.compact
        @credit_data = @credit_data.each_with_index.map{
            |tran,ind| ["T#{ind}",tran]
        }
        @debit_data = @transactions.map{
            |transaction|
        [transaction.amount] if transaction.transaction_type.to_s.eql?("debit")
        }.compact
        @debit_data = @debit_data.each_with_index.map{
            |tran,ind| ["T#{ind}",tran]
        }
    end

    def new
        unless Transaction.last.nil?
          @transaction_amount = Transaction.last.total_balance
        else
            @transaction_amount = 0
        end
    end
    
    def create
        @transaction = Transaction.new(post_params)

        if @transaction.save
            redirect_to @transaction
        else
            render plain: 'Unable to store transaction in the database'
        end

    end

    def show
        @transaction = Transaction.find(params[:id])

    end

    def edit

    end
    
    def destroy
        @transaction = Transaction.find(params[:id])
        @transaction.destroy

        redirect_to transactions_path
    end

    private def post_params
        params.require(:post).permit(:transaction_type,:amount,:date_of_transaction,:total_balance,:transaction_account,:comments)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relative_activities_helper.rb
module RelativeActivitiesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/_customJS.html.erb
<script>

var d = new Date();
    var n = d.getFullYear();
    document.getElementById("main-footer1").innerHTML = '&#xa9; '+n+' Sachin S. All rights reserved.';

    var toggle1Flag = false;
$('#toggle1').click(function(){
    toggle1Flag = !toggle1Flag
    
    if(toggle1Flag){
        $('#sidebar-wrapper').animate({width:0,opacity:0});
    $('#main-content-wrapper').animate({left:0});
    }
    else
    {    
    $('#sidebar-wrapper').animate({width:250,opacity:1});
    $('#main-content-wrapper').animate({left:250});
    }
});
<% if user_signed_in? %>
 $('#toggle1').click();
 $('#toggle1').click();
<% end %>


</script>

app/views/layouts/_footer.html.erb
<nav class="navbar fixed-bottom navbar-dark bg-primary">
  <a class="navbar-brand" href="#" id="main-footer1"></a>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar fixed-top navbar-dark bg-primary shadow">
<%if user_signed_in?%>
<button class="btn btn-secondary" id="toggle1"><i class="fas fa-bars"></i></button>
<% end %>
  <a class="navbar-brand" href="<%=transactions_path%>"> Bank </a>
 
  <%if user_signed_in?%>
  
  <%= link_to("Log out",destroy_user_session_path, method: :delete,class:'btn btn-secondary')%>
  
  <% end %>
</nav>

app/views/layouts/_sidebar.html.erb
<nav class="sidebar">

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="/notify.min.js"></script>

    </head>

  <body>
    <%= render 'layouts/header' %>



    <% if user_signed_in? %>
    <div id="sidebar-wrapper" class="bg-secondary">
      <ul class="nav flex-column text-white">
        <li><%= link_to("New Transaction",new_transaction_path,class:'text-white') %></li>
        <li><%= link_to("Transaction Analysis",transactions_path,class:'text-white') %></li>
        <li><%= link_to("Activity Entry",new_relative_activity_path,class:'text-white') %></li>
        <li><%= link_to("Activities Dashboard",relative_activities_path,class:'text-white') %></li>
        <li><a>About</a></li>
      </ul>
    </div>
    <% end %>

    <div id="main-content-wrapper" class="bg-light">
    <% if notice %>
    <script>$.notify("<%= notice %>", "info");</script>
    <% end %>
    <% if alert %>
    <script>$.notify("<%= alert %>", "warn");</script>
    <% end %>


        <%= yield %>

    </div>
    
    </div>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/customJS'%>
  </body>
</html>

app/views/relative_activities/_empty_list.html.erb
<%# app/views/application/_empty_list.html.erb %>
<div class="row">
<div class="col"></div>
<div class="col">
<%= image_tag("empty.png", :alt => "rss feed",:width=>600) %>
</div>
<div class="col"></div>
</div>

app/views/relative_activities/index.html.erb
<%if @ractivities.empty? %>
<br><br>
  <%= render "empty_list" %>
<% else %>
<h1>Relative Activities</h1>
<br>
<div class="row">
<div class="col-sm-4">
<%= line_chart [
  {:name=>"Meditation",:data=>@med_data},
  {:name=>"Minnimum pass value",:data=>@min_data}
  
  ],max:10,id:'ch5' %>
  </div>
  <div class="col-sm-4">
  <%= line_chart [
    {:name=>"Exercise",:data=>@exer_data},
    {:name=>"Minnimum pass value",:data=>@min_data}
  
  ],max:10,id:'ch6' %>
  </div>
  <div class="col-sm-4">
  <%= line_chart [
    {:name=>"Reading",:data=>@read_data},
    {:name=>"Minnimum pass value",:data=>@min_data}
  ],max:10,id:'ch7' %>
  </div>
  
  </div>
<div class="row">
<div class="col-sm-4">
<%= line_chart [{:name=>"Concentration",:data=>@conc_data},
{:name=>"Minnimum pass value",:data=>@min_data}],max:10,id:'ch8' %>
  </div>
  <div class="col-sm-4">
  <%= line_chart [ {:name=>"Hard Working",:data=>@hard_data},
  {:name=>"Minnimum pass value",:data=>@min_data}
  ],max:10,id:'ch9' %>
  </div>
  <div class="col-sm-4">
  <%= line_chart [
    {:name=>"Mental Stability",:data=>@metal_data},
    {:name=>"Minnimum pass value",:data=>@min_data}
  ],max:10,id:'ch10' %>
  </div>
  
  </div>

  <div class="row">
  <div class="col-sm-4">
  <%= line_chart [{:name=>"Self Confidence",:data=>@self_data},
  {:name=>"Minnimum pass value",:data=>@min_data}
  ],max:10,id:'ch11' %>
    </div>
    <div class="col-sm-4">
    <%= line_chart [ {:name=>"Time Management",:data=>@time_data},
    {:name=>"Minnimum pass value",:data=>@min_data}
    
    ],max:10,id:'ch12' %>
    </div>
    <div class="col-sm-4">
    <%= line_chart [
      {:name=>"Universal Power",:data=>@univ_data},
      {:name=>"Minnimum pass value",:data=>@min_data}
    ],max:10 ,id:'ch13' %>
    </div>
    
    </div>



<div class="row">
<div class="col-md-3">
<input type="radio" value="" name="colorDecider" id="colorcheck1">
  <label>
    Color based on value
  </label></input>
  </div>
  <div class="col-md-3">
  <input type="radio" value=""  name="colorDecider" id="colorcheck2">
  <label>
    Disable color
  </label></input>
  </div>
</div>
<br>
<table class='table table-striped' id="ractivity1">
  <tr><th>Entry Date</th><th>Medit</th><th>Exer</th><th>Read</th><th>Conc</th><th>Hard</th><th>Ment</th><th>Self</th><th>Time</th><th>Univ</th><th>Total</th><th>Actions</th></tr>

  <% @ractivities.each do |ractivity| %>
    <tr>
        <td><%= ractivity.entry_date %></td>
        <td class="markc"><%= ractivity.meditation   %></td>
        <td class="markc"><%= ractivity.exercise  %></td>
        <td class="markc"><%= ractivity.reading %></td>
        <td class="markc"><%= ractivity.concentration %></td>
        <td class="markc"><%= ractivity.hard_working  %></td>
        <td class="markc"><%= ractivity.metal_stability  %></td>
        <td class="markc"><%= ractivity.self_confidene  %></td>
        <td class="markc"><%= ractivity.time_management  %></td>
        <td class="markc"><%= ractivity.universal_power  %></td>
        <td class="markd"><%= ractivity.totalScore  %></td>
        <td><%= link_to("Show",ractivity,class:'btn btn-primary') %> <%= link_to "Delete", ractivity, method: :delete, data: { confirm: "Are you sure?" },class:'btn btn-primary' %></td>
    </tr>
  <% end %>
</table>

<% end %>
<script>
function myColorFunc(){
$('#ractivity1 td.markc').each(function(){
  if (Number($(this).text()) <= 5) {
      $(this).css('background-color','#ffcccc');
  }
else{
 
  $(this).css('background-color','#ccffcc');
}
});
$('#ractivity1 td.markd').each(function(){
  if (Number($(this).text()) <= 40 ) {
      $(this).css('background-color','#ffcccc');
  }
else{
 
  $(this).css('background-color','#ccffcc');
}
});

}
$('#colorcheck1').click(myColorFunc);
$('#colorcheck2').click(function(){

$('#ractivity1 td.markc').each(function(){
        $(this).css('background-color','initial');
});
$('#ractivity1 td.markd').each(function(){
        $(this).css('background-color','initial');
});


});

</script>

app/views/relative_activities/new.html.erb
<%= form_for :post, url: relative_activities_path,:html => {:class => "form-horizontal center"} do |f| %>

    <div class="form-row">
    <div class="form-group col-md-4">
    <%= f.label :entry_date, "Date :" %>
    <%= f.date_field :entry_date,class: 'form-control' %>
    </div>
    <div class="form-group col-md-4">
        <%= f.label :meditation ,"Meditation : "%>
        <%= f.number_field :meditation,class: 'form-control',:min=>0,:max=>10,:required=>true %>
    </div>
    <div class="form-group col-md-4">
        <%= f.label :exercise ,"Exercise : "%>
        <%= f.number_field :exercise,class: 'form-control',:min=>0,:max=>10,:required=>true %>
    </div>
    </div>
    <div class="form-row">
    <div class="form-group col-md-4">
        <%= f.label :reading ,"Reading : "%>
        
        <%= f.number_field :reading,class: 'form-control',:min=>0,:max=>10,:required=>true %>
        
    </div>
    <div class="form-group col-md-4">
        <%= f.label :concentration ,"Concentration : "%>
        
        <%= f.number_field :concentration,class: 'form-control',:min=>0,:max=>10,:required=>true %>
        
    </div>
    <div class="form-group col-md-4">
        <%= f.label :hard_working ,"Hard Working : "%>
        
        <%= f.number_field :hard_working,class: 'form-control',:min=>0,:max=>10,:required=>true %>
        
    </div>
    </div>
    <div class="form-row">
    <div class="form-group col-md-4">
        <%= f.label :metal_stability ,"Mental Stability : "%>
        
        <%= f.number_field :metal_stability,class: 'form-control',:min=>0,:max=>10,:required=>true %>
        
    </div>
    <div class="form-group col-md-4">
        <%= f.label :self_confidene ,"Self Confidence : "%>
       
        <%= f.number_field :self_confidene,class: 'form-control',:min=>0,:max=>10,:required=>true %>
        
    </div>
    <div class="form-group col-md-4">
        <%= f.label :time_management ,"Time Management : "%>
        
        <%= f.number_field :time_management,class: 'form-control',:min=>0,:max=>10,:required=>true %>
        
    </div>
    </div>
    <div class="form-row">
    <div class="form-group col-md-4">
        <%= f.label :universal_power ,"Universal Power : "%>
        
        <%= f.number_field :universal_power,class: 'form-control',:min=>0,:max=>10,:required=>true %>
        
    </div>
    </div>
    <%= f.submit "Submit",class: 'btn btn-primary' %>
<% end %>

<script>
document.getElementById("post_entry_date").valueAsDate = new Date();
</script>

app/views/relative_activities/show.html.erb
<h1> Activity details </h1>
<table class="table table-bordered">
<tr><td>Entry Date</td><td><%= @ractivity.entry_date  %></td></tr>
<tr><td>Meditation</td><td><%= @ractivity.meditation  %></td></tr>
<tr><td>Exercise</td><td><%= @ractivity.exercise  %></td></tr>
<tr><td>Reading</td><td><%= @ractivity.reading %></td></tr>
<tr><td>Concentration</td><td><%= @ractivity.concentration %></td></tr>
<tr><td>Hard Working</td><td><%= @ractivity.hard_working  %></td></tr>
<tr><td>Mental Stability</td><td><%= @ractivity.metal_stability  %></td></tr>
<tr><td>Self Confidence</td><td><%= @ractivity.self_confidene  %></td></tr>
<tr><td>Time Management</td><td><%= @ractivity.time_management  %></td></tr>
<tr><td>Universal Power</td><td><%= @ractivity.universal_power  %></td></tr>
<tr><td>Total Score</td><td><%= @ractivity.totalScore  %></td></tr>
</table>
<%= link_to("Main page",relative_activities_path, class:'btn btn-primary') %>

app/views/transactions/_empty_list.html.erb
<%# app/views/application/_empty_list.html.erb %>
<div class="row">
<div class="col"></div>
<div class="col">
<%= image_tag("empty.png", :alt => "rss feed",:width=>600) %>
</div>
<div class="col"></div>
</div>

app/views/transactions/index.html.erb
<%if @transactions.empty? %>
<br><br>
  <%= render "empty_list" %>
<% else %>
<h1>Transaction home page</h1>
<div class="row">
<div class="col-sm-6 card graph-css">
<div>
  <select class="custom-select" id="inputGroupSelect04">
    <option selected>Choose query...</option>
    <option value="1">Show Both Credit/Debit Transactions</option>
    <option value="2">Only Debit Transactions</option>
    <option value="3">Only Credit Transactions</option>
  </select>
  <br><br>
  </div>

<%= line_chart [{:name=>"Credit",:data=>@credit_data},{:name=>"Debit",:data=>@debit_data}],id:'ch1' %>
<%= line_chart @debit_data,id:'ch2' %>
<%= line_chart @credit_data,id:'ch3' %>

</div>
<div class="col-sm-6 card graph-css">
<div>
  <select class="custom-select" id="inputGroupSelect05">
    <option selected>Choose query...</option>
    <option value="1">Show Both Credit/Debit Transactions</option>
    <option value="2">Only Debit Transactions</option>
    <option value="3">Only Credit Transactions</option>
  </select>
  <br><br>
  </div>

<%= column_chart [{:name=>"Credit",:data=>@credit_data},{:name=>"Debit",:data=>@debit_data}],id:'clh1' %>
<%= column_chart @debit_data,id:'clh2' %>
<%= column_chart @credit_data,id:'clh3' %>
</div>
</div>
<br>
<div class="container">
<table class='table table-striped'>
  <tr><th>Transaction Type</th><th>Amount</th><th>Date</th><th>Total balance</th><th>transaction_account</th><th>comments</th><th>Actions</th></tr>

  <% @transactions.each do |transaction| %>
    <tr>
        <td><%= transaction.transaction_type  %></td>
        <td><%= transaction.amount  %></td>
        <td><%= transaction.date_of_transaction  %></td>
        <td><%= transaction.total_balance %></td>
        <td><%= transaction.transaction_account %></td>
        <td><%= transaction.comments  %></td>
        <td><%= link_to("Show",transaction,class:'btn btn-primary') %> <%= link_to "Delete", transaction, method: :delete, data: { confirm: "Are you sure?" },class:'btn btn-primary' %></td>
    </tr>
  <% end %>
<%end%>
</table>
</div>
<script>
$('#ch2').hide();

$('#ch3').hide();

$('#inputGroupSelect04').change(function(){
  if($('#inputGroupSelect04').val() == "1") {
    $('#ch1').show(); 
    $('#ch2').hide(); 
    $('#ch3').hide(); 
  }
  if($('#inputGroupSelect04').val() == "2") {
    $('#ch1').hide(); 
    $('#ch2').show(); 
    $('#ch3').hide(); 
  }
  if($('#inputGroupSelect04').val() == "3") {
    $('#ch1').hide(); 
    $('#ch2').hide(); 
    $('#ch3').show(); 
  }
});

$('#clh2').hide();

$('#clh3').hide();

$('#inputGroupSelect05').change(function(){
  if($('#inputGroupSelect05').val() == "1") {
    $('#clh1').show(); 
    $('#clh2').hide(); 
    $('#clh3').hide(); 
  }
  if($('#inputGroupSelect05').val() == "2") {
    $('#clh1').hide(); 
    $('#clh2').show(); 
    $('#clh3').hide(); 
  }
  if($('#inputGroupSelect05').val() == "3") {
    $('#clh1').hide(); 
    $('#clh2').hide(); 
    $('#clh3').show(); 
  }
});
</script>

app/views/transactions/new.html.erb
<%= form_for :post, url: transactions_path,:html => {:class => "form-horizontal center"} do |f| %>
    <div class="form-group row">
    <%= f.label "Transaction type : ",class: "col-sm-2 col-form-label"%>

    <div class="col-sm-10">
    <div class="form-check form-check-inline">

    <%= f.radio_button :transaction_type, 'credit',class:"form-check-input", :checked => true %> 
    <%= f.label :transaction_type ,"Credit",class: "form-check-label"%>

    </div>


    <div class="form-check form-check-inline">

    <%= f.radio_button :transaction_type, 'debit',class:"form-check-input" %> 
    <%= f.label :transaction_type ,"Debit",class: "form-check-label"%>

    </div>
    </div>
    </div>
    

    <div class="form-group row">
        <%= f.label :amount ,"Amount : ",class: "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
        <%= f.number_field :amount, step: :any,class: 'form-control',:required=>true %>
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :date_of_transaction, "Date :",class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
        <%= f.date_field :date_of_transaction,class: 'form-control' %>
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :total_balance ,"Total balance : ",class: "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
        <%= f.number_field :total_balance, step: :any,class: 'form-control',:readonly=>true %>
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :transaction_account ,"Account Name : ",class: "col-sm-2 col-form-label"%>
        <div class="col-sm-10">
        <%= f.text_field :transaction_account,class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :comments ,"comments : ",class: "control-label"%>
        <%= f.text_area :comments, rows: "5",class: 'form-control' %>
    </div>

        <%= f.submit "Create",class: 'btn btn-primary' %>
  <% end %>
  <script>
  var t_amount = <%=@transaction_amount%>;
  document.getElementById("post_date_of_transaction").valueAsDate = new Date();
  document.getElementById("post_comments").innerHTML = "Daily spending";
  document.getElementById("post_transaction_account").value = "Bank account";
  document.getElementById("post_total_balance").value = t_amount;
  function myCordFunc(){
    var cord = $('input[name="post[transaction_type]"]:checked').val();
    if(cord=="credit")
        {
            document.getElementById("post_total_balance").value = (Number(t_amount) + Number(document.getElementById("post_amount").value)).toString().replace(/^0+/, '');
        }
    if(cord=="debit")
        {
            document.getElementById("post_total_balance").value = (Number(t_amount) - Number(document.getElementById("post_amount").value)).toString().replace(/^0+/, '');;
        }
  }
  $('#post_amount').change(function(){
    myCordFunc();
  });
  $('input[name="post[transaction_type]"]').change(function(){
      myCordFunc();
  }
);
  
  </script>

app/views/transactions/show.html.erb
<h1> Transaction details </h1>
<table class="table">
<tr><td>Transaction Type</td><td><%= @transaction.transaction_type  %></td></tr>
<tr><td>Amount</td><td><%= @transaction.amount  %></td></tr>
<tr><td>Date</td><td><%= @transaction.date_of_transaction  %></td></tr>
<tr><td>Total balance</td><td><%= @transaction.total_balance %></td></tr>
<tr><td>transaction_account</td><td><%= @transaction.transaction_account %></td></tr>
<tr><td>comments</td><td><%= @transaction.comments  %></td></tr>
</table>
<%= link_to("Main page",transactions_path, class:'btn btn-primary') %>